server:
  port: 8099
spring:
  profiles:
    active: develop-work
---
spring:
  profiles: develop-home
  #  Database configurations
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tictactoe?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
---
spring:
  profiles: develop-work
  #  Database configurations
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/tictactoe?characterEncoding=UTF-8&useSSL=false
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
---
